# Generated by Django 4.2.29 on 2026-04-03 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumoCloud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa_id', models.IntegerField()),
                ('empresa_nombre', models.CharField(max_length=100)),
                ('proveedor', models.CharField(max_length=20)),
                ('servicio', models.CharField(max_length=100)),
                ('costo', models.DecimalField(decimal_places=4, max_digits=12)),
                ('mes', models.IntegerField()),
                ('anio', models.IntegerField()),
                ('region', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
